############################################################################
# apps/examples/encoder/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_ENCODER_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_ENCODER_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_ENCODER_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_ENCODER)

MAINSRC = encoder_main.c position_sensor.c

include $(APPDIR)/Application.mk

