name: Robotics CI/CD

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  nuttx-build-smoke:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/dheerajsingh1107/nuttx-ci:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix git safe directory
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Configure + Build
        run: |
          cd nuttx
          ./tools/configure.sh -a ../nuttx-apps sim:nsh
          make olddefconfig
          make -j$(nproc)

      - name: Run simulation
        run: |
          cd nuttx
          chmod +x ./nuttx
          timeout 15s ./nuttx > ../sim.log 2>&1 || true

      - name: Verify NSH
        run: |
          grep -q "nsh>" sim.log